Use Q_DECL_EXPORT instread of KSERVICE_EXPORT in K_EXPORT_PLUGIN_VERSION
Using KSERVICE_EXPORT causes errors on Windows since it expands to
__declspec(dllimport) or __declspec(dllexport) depending on whether it is
being build or the header is being used. Since we are not building KService
when K_EXPORT_PLUGIN_VERSION is being used we get the following error:
error C2491: 'kde_plugin_version' : definition of dllimport data not allowed

REVIEW: 117089